import org.junit.Test;
import static org.junit.Assert.*;

public class FullAppTest {
    //Registration test for username
    @Test
    public void testValiduserName() {// Test if username is valid
        Registration reg = new Registration();
        assertTrue(reg.checkuserName("abcdef_"));// valid <= chars and contains "_"

    }

    @Test
    public void testInvaliduserNameTooLong() {// test if the username is not too long
        Registration reg = new Registration();
        assertFalse(reg.checkuserName("abcdef_")); // too long
    }

    @Test
    public void testInvaliduserNameNoUnderscore() {//test if the username does not have an underscore
        Registration reg = new Registration();
        assertFalse(reg.checkuserName("abcd"));// missing an underscore
    }

    // Registration: Password tests
    @Test
    public void testValidPassword() {// test if password is valid
        Registration reg = new Registration();
        assertTrue(reg.checkPasword("Passw0rd!")); // password has an uppercase, a number and a special character

    }

    @Test
    public void testInvalidPasswordTooShort() {// test if password is not too short
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Pw1!")); // The password is too short
    }

    @Test
    public void testInvalidPasswordNoUppercase() {// check if password contains an uppercase
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("password1")); // does not have an uppercase letter
    }

    @Test
    public void testInvalidPasswordNoDigit() {// test if password contains a digit
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Password!"));// missing digit
    }

    @Test
    public void testInvalidPasswordNoSpecialChar() {// tests if the password contains a special character
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Password1")); // missing a special character
    }

    //Registration Phone number tests
    @Test
    public void testValidPhoneNumberLocal() {// if phone number is local and starts with a 0 and contains 9 digits
        Registration reg = new Registration();
        assertTrue(reg.checkphoneNumber("0123456789")); // STARTS WITH 0 + 9 digits
    }

    @Test
    public void testValidPhoneNumberInternational() {// the phone number should contain a country code e.g +27
        Registration reg = new Registration();
        assertTrue(reg.checkphoneNumber("+27123456789")); // Starts with +27 + 9 digits
    }

    @Test
    public void testInvalidPhoneNumberTooShort() {
        Registration reg = new Registration();
        assertFalse(reg.checkphoneNumber("12345")); // phone number is too short
    }

    @Test
    public void testInvalidPhoneNumberWrongPrefix() {
        Registration reg = new Registration();
        assertFalse(reg.checkphoneNumber("9912345678")); // wrong prefix
    }

    //Login: Successful login
    @Test
    public void testSuccessfulLogin() {
        Login login = new Login("user123", "pass123", "John", "Doe");
        String result = login.loginUser("user123", "pass123");

    }

    // Login : Filed Login
    @Test
    public void testFailedLogin() {
        Login login = new Login("user123", "pass123", "John", "Does");
        String result = login.loginUser("wrongUser", "wrongPass");
    }
    // Part 2: Message Tests
    //Test if the user's message is under 250 words
    @Test
    public void testMessageLengthSuccess() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        String message = "Hi Mike, can you join us for dinner tonight?";
        assertTrue(message.length() <= 250);
    }
//test that a message that is over 250 words should return an error message
    @Test
    public void testMessageLengthFailure() {
        String message = "a".repeat(251);
        Message msg = new Message("+27718693002",message);

        assertFalse(message.length() <= 250);
    }
// tests if the recipient number is formatted correctly
    @Test
    public void testRecipientSuccess() {
        Message msg = new Message("+27718693002","Hi Mike, can you join us for dinner tonight?");
        assertEquals(true,
                msg.checkRecipientCell());
    }
// tests when an incorrectly formatted recipient number is formatted incorrectly
    @Test
    public void testRecipientInvalidNumber() {
        Message msg = new Message("085759758889", "Hi Keegan, did you receive the payment?");
        assertEquals(false,
                msg.checkRecipientCell());
    }
// message ID hash
    //Test that a message ID is autogenerated and not equal to zero
    @Test
    public void testMessageHash() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        assertEquals("00:1:HITONIGHT",
                msg.createMessageHash(1));
    }
// test that choosing the send option returns the right success message
    @Test
    public void testSentMessageSend() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        assertEquals("Message Successfully Sent", msg.sentMessage());
    }
// test that choosing the discard option returns the correct discard message
    @Test
    public void testSentMessageDisregard() {
        Message msg = new Message("085759758889", "Hi Keegan, did you receive the payment?");
        assertEquals("Message Successfully Sent",
                msg.sentMessage());
    }
// test that choosing the store otpion returns the correct store message
    @Test
    public void testSentMessageStore() {
        Message msg = new Message("+27718693002", "Stored message test");
        assertEquals("Message Successfully Sent",
                msg.sentMessage());
    }


}
