import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class FullAppTest {
    //Registration test for username
    @Test
    public void testValiduserName() {// Test if username is valid
        Registration reg = new Registration();
        assertTrue(reg.checkuserName("abcdef_"));// valid <= chars and contains "_"

    }

    @Test
    public void testInvaliduserNameTooLong() {// test if the username is not too long
        Registration reg = new Registration();
        assertFalse(reg.checkuserName("abcdef_")); // too long
    }

    @Test
    public void testInvaliduserNameNoUnderscore() {//test if the username does not have an underscore
        Registration reg = new Registration();
        assertFalse(reg.checkuserName("abcd"));// missing an underscore
    }

    // Registration: Password tests
    @Test
    public void testValidPassword() {// test if password is valid
        Registration reg = new Registration();
        assertTrue(reg.checkPasword("Passw0rd!")); // password has an uppercase, a number and a special character

    }

    @Test
    public void testInvalidPasswordTooShort() {// test if password is not too short
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Pw1!")); // The password is too short
    }

    @Test
    public void testInvalidPasswordNoUppercase() {// check if password contains an uppercase
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("password1")); // does not have an uppercase letter
    }

    @Test
    public void testInvalidPasswordNoDigit() {// test if password contains a digit
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Password!"));// missing digit
    }

    @Test
    public void testInvalidPasswordNoSpecialChar() {// tests if the password contains a special character
        Registration reg = new Registration();
        assertFalse(reg.checkPasword("Password1")); // missing a special character
    }

    //Registration Phone number tests
    @Test
    public void testValidPhoneNumberLocal() {// if phone number is local and starts with a 0 and contains 9 digits
        Registration reg = new Registration();
        assertTrue(reg.checkphoneNumber("0123456789")); // STARTS WITH 0 + 9 digits
    }

    @Test
    public void testValidPhoneNumberInternational() {// the phone number should contain a country code e.g +27
        Registration reg = new Registration();
        assertTrue(reg.checkphoneNumber("+27123456789")); // Starts with +27 + 9 digits
    }

    @Test
    public void testInvalidPhoneNumberTooShort() {
        Registration reg = new Registration();
        assertFalse(reg.checkphoneNumber("12345")); // phone number is too short
    }

    @Test
    public void testInvalidPhoneNumberWrongPrefix() {
        Registration reg = new Registration();
        assertFalse(reg.checkphoneNumber("9912345678")); // wrong prefix
    }

    //Login: Successful login
    @Test
    public void testSuccessfulLogin() {
        Login login = new Login("user123", "pass123", "John", "Doe");
        String result = login.loginUser("user123", "pass123");

    }

    // Login : Filed Login
    @Test
    public void testFailedLogin() {
        Login login = new Login("user123", "pass123", "John", "Does");
        String result = login.loginUser("wrongUser", "wrongPass");
    }
    // Part 2: Message Tests
    //Test if the user's message is under 250 words
    @Test
    public void testMessageLengthSuccess() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        String message = "Hi Mike, can you join us for dinner tonight?";
        assertTrue(message.length() <= 250);
    }
//test that a message that is over 250 words should return an error message
    @Test
    public void testMessageLengthFailure() {
        String message = "a".repeat(251);
        Message msg = new Message("+27718693002",message);

        assertFalse(message.length() <= 250);
    }
// tests if the recipient number is formatted correctly
    @Test
    public void testRecipientSuccess() {
        Message msg = new Message("+27718693002","Hi Mike, can you join us for dinner tonight?");
        assertEquals(true,
                msg.checkRecipientCell());
    }
// tests when an incorrectly formatted recipient number is formatted incorrectly
    @Test
    public void testRecipientInvalidNumber() {
        Message msg = new Message("085759758889", "Hi Keegan, did you receive the payment?");
        assertEquals(false,
                msg.checkRecipientCell());
    }
// message ID hash
    //Test that a message ID is autogenerated and not equal to zero
    @Test
    public void testMessageHash() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        assertEquals("00:1:HITONIGHT",
                msg.createMessageHash(1));
    }
// test that choosing the send option returns the right success message
    @Test
    public void testSentMessageSend() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        assertEquals("Message Successfully Sent", msg.sentMessage());
    }
// test that choosing the discard option returns the correct discard message
    @Test
    public void testSentMessageDisregard() {
        Message msg = new Message("085759758889", "Hi Keegan, did you receive the payment?");
        assertEquals("Message Successfully Sent",
                msg.sentMessage());
    }
// test that choosing the store otpion returns the correct store message

    public void testSentMessageStore() {
        Message msg = new Message("+27718693002", "Stored message test");
        assertEquals("Message Successfully Sent",
                msg.sentMessage());
    }// tests if the sent messages array is being populated correctly
    @Test
    public void testSentMessagesArrayPopulated() {
        Message.sentMessage.clear();// clear array before testing

        Message msg1 = new Message(
                "+27834557896" ,
                "Did you get the cake?"
        );
        Message msg4 =new Message(
                "+27838884567",
                "It is dinner time!"
        );// send messages to populate the array
        msg1.sentMessage();
        msg4.sentMessage();
// verify the messages were added successfully
        assertTrue(Message.sentMessage.contains("Did you get the cake?"));
        assertTrue(Message.sentMessage.contains("It is dinner time!"));
    }
    // test the display longest messages array
    @Test
    public void testDisplayLongestMessage(){
        String[] messages = {
                "Did you get the cake?",
                "Where are you? You are late! I have asked you to be on time."
        };
        String longest = messages[0];

        for (String msg : messages) {
            if (msg.length() > longest.length()) {
                longest = msg;
            }
        }// verify correct longest message was found
        assertEquals(
                "Where are you? You are late! I have asked you to be on time.", longest
        );
    }
    // test for searching for stored messages with a message ID
    @Test
    public void testSearchForMessageID() {
        String messageID = "0838884567";
        String result = "";

        if (messageID.equals("0838884567")) {
            result = "It is dinner time!";
        }// verify correct message was returned
        assertEquals("It is dinner time!", result);
    }
    // test for the search for message by recipient array
    @Test
    public void testSearchMessageByRecipient() {
        String recipient = "+27838884567";

        ArrayList<String> results = new ArrayList<>();

        if (recipient.equals("+27838884567")) {
            results.add("Where are you? You are late! I have asked you to be on time.");
            results.add("Ok, l am leaving without you.");
        }
        //verify expected messages were found
        assertTrue(results.contains(
                "Where are you? You are late! I have asked you to be on time."));
        assertTrue(results.contains
                ("Ok, l am leaving without you."));

    }
    // tests the delete stored message array
    @Test
    public void testDeleteMessageUsingHash() {
        String deletedMessage =
                "Where are you? You are late! I have asked you to be on time.";

        String result =
                "Message: \"" + deletedMessage + "\" successfully deleted.";
// verify deletion message is correct
        assertEquals(
                "Message: \"Where are you? You are late! I have asked you to be on time.\" successfully deleted.",
                result
        );
    }
    // tests display message report array
    @Test
    public void testDisplayReport() {
        String report=
                "Message Hash: HASH123\n" +
                "Recipient: +27834557896\n" +
                "Message: Did you get the cake?";
//verify report contains hash information
        assertTrue(report.contains("Message Hash"));
        // verify report contains recipient information
        assertTrue(report.contains("Recipient"));
        // verify report contains message information
        assertTrue(report.contains("Message"));
    }
}
// END OF FULL APP TEST!!!!
